"""Add wired device support to Wi-Fi Stalker

Revision ID: 9ded46fa11ea
Revises: 48205017a8b9
Create Date: 2025-12-05 22:08:24.868535+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ded46fa11ea'
down_revision: Union[str, None] = '48205017a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stalker_connection_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_wired', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('switch_mac', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('switch_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('switch_port', sa.Integer(), nullable=True))

    with op.batch_alter_table('stalker_tracked_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_wired', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('current_switch_mac', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_switch_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_switch_port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stalker_tracked_devices', schema=None) as batch_op:
        batch_op.drop_column('current_switch_port')
        batch_op.drop_column('current_switch_name')
        batch_op.drop_column('current_switch_mac')
        batch_op.drop_column('is_wired')

    with op.batch_alter_table('stalker_connection_history', schema=None) as batch_op:
        batch_op.drop_column('switch_port')
        batch_op.drop_column('switch_name')
        batch_op.drop_column('switch_mac')
        batch_op.drop_column('is_wired')

    # ### end Alembic commands ###
